### Домашнее задание к уроку 5

*1. Найти с помощью NumPy SVD для матрицы:*

In [1]:
#     1 2 0
#     0 0 5
#     3 -4 2
#     1 6 5
#     0 1 0

In [2]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [3]:
A = np.array([[1, 2, 0], 
              [0, 0, 5], 
              [3, -4, 2], 
              [1, 6, 5], 
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [4]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [5]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [6]:
# То же самое, только в виде значений:
print(s)

[8.82 6.14 2.53]


In [7]:
print(U)

[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [8]:
print(V)

[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


*2. Для матрицы из предыдущего задания найти:*

**а) евклидову норму**

In [9]:
# Евклидова норма матрицы А равна ее максимальному сингулярному числу.
# Максимальное сингулярное число матрицы можно получить с помощью функции "numpy.linalg.norm",
# если указать параметр "ord=2":

In [10]:
np.linalg.norm(A, ord=2)

8.824868854820444

In [11]:
# Полученное значение совпадает с максимальным значением в матрице D из задания 1.

**б) норму Фробениуса**

In [12]:
# Норму Фробениуса матрицы А можно получить с помощью функции "numpy.linalg.norm", если указать параметр "ord=2",
# "ord=None" либо ничего не указывать. Она установлена по умолчанию. В результате мы получим значение, 
# равное квадратному корню из суммы квадратов модулей элементов матрицы.

In [13]:
np.linalg.norm(A, ord='fro')

11.045361017187261

In [14]:
np.linalg.norm(A, ord=None)

11.045361017187261

In [15]:
np.linalg.norm(A)

11.045361017187261