### Задание к уроку 2

**5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.**

In [27]:
# Создадим две матрицы А=3х3 и В=3х4 и перемножим их используя NumPy.
# В результате получим матрицу размером 3х4.
# Полученный результат будем использовать для проверки корректности работы нашей функции.

In [28]:
import numpy as np

In [29]:
A = np.array([[14, 7, 4], [3, 5, 8], [9, 8, 7]])
B = np.array([[6, 7, 1, 2], [7, 6, 4, 0], [4, 5, 8, 2]])

print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')
print(f'Матрица AB\n{A @ B}')

Матрица A
[[14  7  4]
 [ 3  5  8]
 [ 9  8  7]]

Матрица B
[[6 7 1 2]
 [7 6 4 0]
 [4 5 8 2]]

Матрица AB
[[149 160  74  36]
 [ 85  91  87  22]
 [138 146  97  32]]


In [30]:
# Будем использовать вложенные списки:

result = [[sum(a * b for a, b in zip(A_row, B_col)) 

                        for B_col in zip(*B)]

                                for A_row in A]

  

for r in result:

    print(r)

[149, 160, 74, 36]
[85, 91, 87, 22]
[138, 146, 97, 32]
